define:
  ip: localhost:3306
  name: testdb

# Spring Boot Configuration
spring:
  # 1. Spring Boot JDBC + HikariCP 설정
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${define.ip}/${define.name}?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&autoReconnect=true&createDatabaseIfNotExist=true
      username: root
      password: maria123
      pool-name: Hikari Connection Pool # Alias
      maximum-pool-size: 5

      # Connection pool settings
      connection-timeout: 30000 # default 30000 (30 seconds)
      idle-timeout: 600000 # default 600000 (10 minutes)
      max-lifetime: 1800000 # default 1800000 (30 minutes)
      minimum-idle: 5 # default same as maximum-pool-size

      # MariaDB specific properties
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

      # driver-class-name: org.postgresql.Driver
      # jdbc-url: jdbc:postgresql://localhost:5432/testdb
      # username: postgres
      # password: postgres123
      # pool-name: Hikari Connection Pool # Alias
      # maximum-pool-size: 5

  flyway: 
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations:
      - classpath:db/migration/mysql
      - classpath:db/seed/local
      
springdoc:
  # swagger-ui
  swagger-ui:
    enabled: true

# Spring Boot Log4j2 Configuration
logging:
  # default Logging 프레임워크 설정 파일을 참조
  config: classpath:log4j2/log4j2-local.yml

  # Hikari Connection Pool Debug
  level:
    # Tomcat Internal Log
    org:
      apache:
        tomcat: false
        catalina: false

# Server port
server:
  port: 8080

# Spring Boot Custom Value
# JWT Properties
jwt:
  # 1. spring Boot Security + Key 설정(* 반드시 32이상 글자로 구성되어야 함)
  secret-key: 7Hs9x2mK4Lp6Rw3tYzAqBcDfGjNvXeUi
  # 2. JWT Token Expiration 30분
  access-token-expiration-min: 30
  # 3. JWT Token Expiration 7일
  refresh-token-expiration-day: 7
