
CREATE TABLE TB_USER (
    USER_ID VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ENABLED BOOLEAN DEFAULT TRUE,
    LAST_LOGIN_AT DATETIME,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE TB_ROLE (
    ROLE_ID INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(200),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE TB_USER_ROLE (
    USER_ROLE_ID INT AUTO_INCREMENT,
    USER_ID VARCHAR(50),
    ROLE_ID INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE(ROLE_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_ROLE (USER_ID, ROLE_ID)
);

CREATE TABLE TB_MENU (
    MENU_ID INT AUTO_INCREMENT PRIMARY KEY,
    MENU_NAME VARCHAR(100) NOT NULL,
    MENU_URL VARCHAR(200),
    PARENT_ID INT,
    MENU_ORDER INT DEFAULT 0,
    MENU_ICON VARCHAR(50),
    MENU_TYPE CHAR(1) COMMENT 'G: Group, M: Menu, S: Sub-menu',
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PARENT_ID) REFERENCES TB_MENU(MENU_ID) ON DELETE CASCADE
);

CREATE TABLE TB_ROLE_MENU (
    ROLE_MENU_ID INT AUTO_INCREMENT,
    ROLE_ID INT,
    MENU_ID INT,
    CREATE_PERM BOOLEAN DEFAULT FALSE,
    READ_PERM BOOLEAN DEFAULT TRUE,
    UPDATE_PERM BOOLEAN DEFAULT FALSE,
    DELETE_PERM BOOLEAN DEFAULT FALSE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_MENU_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE(ROLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (MENU_ID) REFERENCES TB_MENU(MENU_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_ROLE_MENU (ROLE_ID, MENU_ID)
);

INSERT INTO `TB_USER` (`USER_ID`, `USER_NAME`, `PASSWORD`, `EMAIL`, `PHONE`, `ENABLED`, `CREATED_AT`, `UPDATED_AT`, `LAST_LOGIN_AT`)
VALUES
	('danyoh', '홍길동', '1234', 'danyoh@naver.com', '010', 1, NULL, NULL, NULL);

-- 기본 역할 생성
INSERT INTO TB_ROLE (ROLE_NAME, DESCRIPTION) VALUES 
('ROLE_ADMIN', '시스템 관리자'),
('ROLE_MANAGER', '매니저'),
('ROLE_USER', '일반 사용자');

-- 메인 메뉴 그룹
INSERT INTO TB_MENU (MENU_NAME, MENU_URL, PARENT_ID, MENU_ORDER, MENU_ICON, MENU_TYPE) VALUES
('대시보드', '/dashboard', NULL, 1, 'dashboard', 'M'),
('시스템 관리', NULL, NULL, 99, 'settings', 'G');

-- 시스템 관리 하위 메뉴
INSERT INTO TB_MENU (MENU_NAME, MENU_URL, PARENT_ID, MENU_ORDER, MENU_ICON, MENU_TYPE) VALUES
('사용자 관리', '/admin/users', 2, 1, 'people', 'M'),
('역할 관리', '/admin/roles', 2, 2, 'security', 'M'),
('메뉴 관리', '/admin/menus', 2, 3, 'menu', 'M');

-- 관리자 역할에 모든 메뉴 권한 부여
INSERT INTO TB_ROLE_MENU (ROLE_ID, MENU_ID, CREATE_PERM, READ_PERM, UPDATE_PERM, DELETE_PERM)
SELECT 1, MENU_ID, TRUE, TRUE, TRUE, TRUE FROM TB_MENU;

-- 매니저 역할에 일부 메뉴 권한 부여
INSERT INTO TB_ROLE_MENU (ROLE_ID, MENU_ID, CREATE_PERM, READ_PERM, UPDATE_PERM, DELETE_PERM)
SELECT 2, MENU_ID, 
  CASE WHEN MENU_NAME = '사용자 관리' THEN FALSE ELSE TRUE END, 
  TRUE, 
  CASE WHEN MENU_NAME = '사용자 관리' THEN FALSE ELSE TRUE END, 
  FALSE 
FROM TB_MENU;

-- 일반 사용자 역할에 제한된 메뉴 권한 부여
INSERT INTO TB_ROLE_MENU (ROLE_ID, MENU_ID, READ_PERM)
VALUES (3, 1, TRUE); -- 대시보드만 열람 가능

