CREATE TABLE IF NOT EXISTS BS_USER (
    USER_ID VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ENABLED BOOLEAN DEFAULT TRUE,
    LAST_LOGIN_AT DATETIME,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID)
);
